[project]
name = "aiogram-bot"
version = "0.1.0"
readme = "README.md"
requires-python = "==3.13.4"
dependencies = [
    "aiogram[fast,redis]==3.20.0.post0",
    "common-lib[aiogram]",
    "redis[hiredis]==5.2.1",
]

[tool.uv.sources]
common-lib = { path = "src/common_lib" }
